// DAY 1: frontend only. localStorage saves data in the browser.
const products={headphones:{name:"Sony WH-1000XM5 Wireless Noise Cancelling Headphones",emoji:"🎧",saving:"₹3,501",sellers:[["Flipkart","₹24,999","4.5 / 5","Free delivery",true],["Amazon","₹25,490","4.6 / 5","Delivery tomorrow",false],["Croma","₹26,990","4.4 / 5","Free delivery",false],["Reliance Digital","₹28,500","4.3 / 5","Delivery in 2 days",false]]},iphone:{name:"Apple iPhone 15 (128 GB)",emoji:"📱",saving:"₹2,901",sellers:[["Flipkart","₹66,999","4.5 / 5","Free delivery",true],["Amazon","₹68,490","4.6 / 5","Delivery tomorrow",false],["Croma","₹69,900","4.4 / 5","Store pickup",false],["Vijay Sales","₹67,990","4.3 / 5","Delivery in 2 days",false]]},laptop:{name:"ASUS Vivobook Go 15 Laptop",emoji:"💻",saving:"₹3,509",sellers:[["Flipkart","₹52,990","4.4 / 5","Free delivery",true],["Amazon","₹54,499","4.5 / 5","Delivery tomorrow",false],["Croma","₹55,990","4.2 / 5","Free delivery",false],["Reliance Digital","₹56,499","4.1 / 5","Delivery in 3 days",false]]}};
const defaultOrders=[["Amazon","boAt Rockerz 450 Headphones","Arrives today",82],["Flipkart","ASUS Vivobook Go 15","Shipped · arrives 20 Aug",55],["Croma","Samsung 25W Adapter","Delivered · 14 Aug",100]];let activeProduct=products.headphones;let orders=JSON.parse(localStorage.getItem("shopCompareOrders"))||defaultOrders;const modal=document.getElementById("modal");
function showProduct(p){activeProduct=p;productTitle.textContent=p.name;productName.textContent=p.name;document.querySelector(".emoji").textContent=p.emoji;saving.textContent=p.saving;sellerRows.innerHTML=p.sellers.map(s=>`<div class="seller-row"><div><span class="shop">${s[0]}</span>${s[4]?'<span class="best">BEST PRICE</span>':''}<div class="small">Verified marketplace</div></div><div><span class="price">${s[1]}</span><div class="small">incl. taxes</div></div><div class="hide-mobile">${s[2]}<div class="small">seller rating</div></div><div class="hide-mobile">${s[3]}<div class="small">estimated delivery</div></div><button class="deal" onclick="openDeal('${s[0]}')">View deal</button></div>`).join("")}
function searchProduct(){const text=searchInput.value.toLowerCase();const key=text.includes("iphone")?"iphone":text.includes("laptop")?"laptop":(text.includes("head")||text.includes("sony"))?"headphones":null;noResult.style.display=key?"none":"block";sellerRows.style.display=key?"block":"none";if(key)showProduct(products[key])}function openDeal(store){alert(`Demo: real app would open the ${store} product page here.`)}
function renderOrders(){orderCards.innerHTML=orders.map((o,i)=>`<article class="order"><div class="order-top"><span>${o[0]}</span><span>Order #SC-${1001+i}</span></div><h3>${o[1]}</h3><p>${o[2]}</p><div class="bar"><div style="width:${o[3]}%"></div></div><p class="status">${o[3]}% complete</p></article>`).join("")}
function openModal(type){modal.classList.remove("hidden");if(type==="order"){modalTitle.textContent="Add an order";modalForm.innerHTML=`<div class="modal-form"><label>Marketplace<select id="store"><option>Amazon</option><option>Flipkart</option><option>Croma</option><option>Other</option></select></label><label>Product name<input id="newProduct" required placeholder="e.g. Nike Shoes"></label><label>Delivery status<input id="delivery" required placeholder="e.g. Arrives 22 Aug"></label><label>Progress (0–100)<input id="progress" type="number" min="0" max="100" value="20" required></label><button class="submit-button">Save order</button></div>`;modalForm.onsubmit=saveOrder}else{modalTitle.textContent="Create price alert";modalForm.innerHTML=`<div class="modal-form"><p>You will be alerted when price goes below your target.</p><label>Product<input value="${activeProduct.name}" disabled></label><label>Target price (₹)<input id="targetPrice" type="number" min="1" required placeholder="e.g. 24000"></label><button class="submit-button">Save alert</button></div>`;modalForm.onsubmit=saveAlert}}
function saveOrder(e){e.preventDefault();orders.push([store.value,newProduct.value,delivery.value,Number(progress.value)]);localStorage.setItem("shopCompareOrders",JSON.stringify(orders));renderOrders();closeModal()}function saveAlert(e){e.preventDefault();localStorage.setItem("shopCompareAlert",JSON.stringify({product:activeProduct.name,target:targetPrice.value}));alert("Price alert saved in your browser!");closeModal()}function closeModal(){modal.classList.add("hidden")}
searchButton.addEventListener("click",searchProduct);searchInput.addEventListener("keydown",e=>{if(e.key==="Enter")searchProduct()});addOrderButton.addEventListener("click",()=>openModal("order"));alertButton.addEventListener("click",()=>openModal("alert"));document.getElementById("closeModalButton").addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});showProduct(activeProduct);renderOrders();
